from oop import S, T, R, C, Geometric_figure

a = S(10)
b = T(13,12,14)
c = R(10,20)
d = C(15)
# print(a.area())
# print(b.area())
# print(c.area())
# print(d.area())
# print(a.angles)
# print(b.half_perimeter())
# print(c.perimeter())
# print(d.area()+a.area())
g = Geometric_figure()
# print(g.angles)
# print(a.add_area(T(10,10,10)))
# print(b.add_area(R(15, 455)))
# print(a.add_area(43243))
# print(a.add_area('sudhsukdj'))
print(S.angles)
print(C.angles)
print(T.angles)
print(T.name)